apiVersion: apps/v1
kind: Deployment
metadata:
  name: slamboook-and-mongodb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-slambook-and-mongodb
  template:
    metadata:
      labels:
        app: web-slambook-and-mongodb
    spec:
      containers:
        - name: slambook-container
          image: anusocial123/slambook-service-web:v1
          ports:
            - containerPort: 3099
          env:
            - name: MONGO_URL
              value: "mongodb://slambook-service:27017/mydatabase"
        - name: mongodb
          image: mongo:latest
