version: '3.8' # Specify the Docker Compose file version

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3099" # Map host port 3000 to container port 3000
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase # MongoDB connection string
      NODE_ENV: development
    depends_on:
      - mongo # Ensure mongo service starts before the app

  mongo:
    image: mongo:latest # Use the latest MongoDB image
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    volumes:
      - ./data:/data/db # Persist MongoDB data
